Workaround a strange error from g++
There was a warning:
```
[100%] Building CXX object demo/Polyhedron/CMakeFiles/polyhedron_demo.dir/MainWindow.cpp.o
/home/lrineau/Git/cgal/Polyhedron/demo/Polyhedron/MainWindow.cpp: In constructor ‘MainWindow::MainWindow(bool, QWidget*)’:
/home/lrineau/Git/cgal/Polyhedron/demo/Polyhedron/MainWindow.cpp:312:11: error: request for member ‘addDockWidget’ is ambiguous
     this->addDockWidget(Qt::BottomDockWidgetArea, dock);
           ^~~~~~~~~~~~~
In file included from /home/lrineau/Git/cgal/Polyhedron/demo/Polyhedron/MainWindow.h:8:0,
                 from /home/lrineau/Git/cgal/Polyhedron/demo/Polyhedron/MainWindow.cpp:4:
/home/lrineau/Git/cgal/Three/include/CGAL/Three/Three.h:54:8: note: candidates are: void CGAL::Three::Three::addDockWidget(QDockWidget*)
   void addDockWidget(QDockWidget* dock_widget);
        ^~~~~~~~~~~~~
In file included from /usr/include/qt5/QtWidgets/QMainWindow:1:0,
                 from /home/lrineau/Git/cgal/GraphicsView/include/CGAL/Qt/DemosMainWindow.h:31,
                 from /home/lrineau/Git/cgal/Polyhedron/demo/Polyhedron/MainWindow.h:7,
                 from /home/lrineau/Git/cgal/Polyhedron/demo/Polyhedron/MainWindow.cpp:4:
/usr/include/qt5/QtWidgets/qmainwindow.h:166:10: note:                 void QMainWindow::addDockWidget(Qt::DockWidgetArea, QDockWidget*, Qt::Orientation)
     void addDockWidget(Qt::DockWidgetArea area, QDockWidget *dockwidget,
          ^~~~~~~~~~~~~
/usr/include/qt5/QtWidgets/qmainwindow.h:165:10: note:                 void QMainWindow::addDockWidget(Qt::DockWidgetArea, QDockWidget*)
     void addDockWidget(Qt::DockWidgetArea area, QDockWidget *dockwidget);
          ^~~~~~~~~~~~~
```

That is strange, because the call is not ambiguous at all: all three
candidates have different numbers of parameters!

Anyway, the workaround is an explicit qualified call to
`QMainWindow::addDockWidget`.